# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzGRvz8l6O2naoI5KdP9Dv_haRBGVkAR
"""

!pip install pandas scikit-learn matplotlib seaborn

import pandas as pd

df = pd.read_csv("heart.csv")

df.head()

print(df.shape)

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Load data
df = pd.read_csv("heart.csv")

# Hapus duplikat
df.drop_duplicates(inplace=True)

# Feature dan target
X = df.drop("target", axis=1)
y = df["target"]

# Scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

models = {
    "Logistic Regression":
        LogisticRegression(max_iter=1000),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),

    "SVM":
        SVC()
}

results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    results.append([
        name,
        accuracy_score(y_test, pred),
        precision_score(y_test, pred),
        recall_score(y_test, pred),
        f1_score(y_test, pred)
    ])

result_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

print(result_df)

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("heart.csv")

df['target'].value_counts().plot(
    kind='bar'
)

plt.title("Distribusi Target")
plt.xlabel("Target")
plt.ylabel("Jumlah Data")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))

sns.heatmap(
    df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Matrix")
plt.show()

import matplotlib.pyplot as plt

models = [
    "Logistic Regression",
    "Random Forest",
    "SVM"
]

accuracy = [
    0.86,
    0.95,
    0.89
]

plt.bar(models, accuracy)

plt.title("Perbandingan Accuracy")
plt.ylabel("Accuracy")

plt.show()

from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import matplotlib.pyplot as plt

# Ambil nama fitur
feature_names = df.drop("target", axis=1).columns

# Train model
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

# Feature importance
importance = pd.DataFrame({
    'Feature': feature_names,
    'Importance': rf.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance)

# Plot
plt.figure(figsize=(10,6))

plt.barh(
    importance['Feature'],
    importance['Importance']
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Feature Importance Random Forest")

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

metrics = result_df.set_index("Model")

metrics.plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Perbandingan Performa Model")
plt.ylabel("Score")
plt.ylim(0,1)

plt.legend(loc="best")

plt.show()

print(result_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

plt.plot(
    result_df["Model"],
    result_df["Accuracy"],
    marker='o',
    label='Accuracy'
)

plt.plot(
    result_df["Model"],
    result_df["Precision"],
    marker='s',
    label='Precision'
)

plt.plot(
    result_df["Model"],
    result_df["Recall"],
    marker='^',
    label='Recall'
)

plt.plot(
    result_df["Model"],
    result_df["F1 Score"],
    marker='d',
    label='F1 Score'
)

plt.title("Perbandingan Performa Model")
plt.xlabel("Model")
plt.ylabel("Score")

plt.ylim(0, 1)

plt.grid(True)
plt.legend()

plt.show()